// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjLGtZbrQ0DDHcBUfktxCUvvxKnYzyLDY',
    appId: '1:474568865543:web:aa5b010afe6230b248b7a2',
    messagingSenderId: '474568865543',
    projectId: 'bioscan-c6d44',
    authDomain: 'bioscan-c6d44.firebaseapp.com',
    storageBucket: 'bioscan-c6d44.firebasestorage.app',
    measurementId: 'G-Q0X9RQWX0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdiI_lUCOwYZD_Qa0BQs1h0K2079bW2sQ',
    appId: '1:474568865543:android:f65534b93f4b589348b7a2',
    messagingSenderId: '474568865543',
    projectId: 'bioscan-c6d44',
    storageBucket: 'bioscan-c6d44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9wDZ6tbQK6KneXZgCQTGbFV2BoQqnFy4',
    appId: '1:474568865543:ios:4a7fc973e74b83a448b7a2',
    messagingSenderId: '474568865543',
    projectId: 'bioscan-c6d44',
    storageBucket: 'bioscan-c6d44.firebasestorage.app',
    iosBundleId: 'com.example.bioscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjLGtZbrQ0DDHcBUfktxCUvvxKnYzyLDY',
    appId: '1:474568865543:web:19288f611c67bb2f48b7a2',
    messagingSenderId: '474568865543',
    projectId: 'bioscan-c6d44',
    authDomain: 'bioscan-c6d44.firebaseapp.com',
    storageBucket: 'bioscan-c6d44.firebasestorage.app',
    measurementId: 'G-BTYE80QZ2E',
  );

}